Tests facelifted a bit (engine -> Space Test 0.16)

diff --git a/test/_engine/run_case b/test/_engine/run_case
--- a/test/_engine/run_case
+++ b/test/_engine/run_case
@@ -25,7 +25,7 @@ export CASE
 	#! otherwise $? coming from the func. would be reset to 0! :-ooo
 	#! -> "SC2155" (https://github.com/koalaman/shellcheck/wiki/SC2155)
 
-echo "---------------------------------------------------------------"
+echo "--------------------------------------------------------------- $((cases_run + 1))"
 DEBUG "Identified \"$1\" as test case [$CASE] at \"$case_path\""
 echo "CASE \"$CASE\""
 
@@ -59,15 +59,16 @@ build_dir "$TEST_CASE_DIR" || FATAL "Failed to build the test case!" $?
 #-----------------------------------
 # Finally, run (source) the case...
 #-----------------------------------
-failed=0
+exitcode=0
 EXPECT=
 case_variant_counter=0
 
 . "$case_script"
 
-retval=$?; if [ "$retval" != "0" ]; then
-	ERROR "Test script failed with unexpected error $retval!"
-	exit 99
+retval=$?; if [ "$retval" != "0" ] || [ -s "$errfile" ]; then
+	ERROR "Test script unexpectedly crashed (with error $retval)!"
+	echo -e "  `cat \"$errfile\"`"
+	exit 109
 fi
 
 # Find or dyn. regenerate the expfile if defined in a .case script
@@ -100,16 +101,17 @@ normalize_crlf "$expfile"
 normalize_crlf "$outfile"
 
 #echo diff -b "$outfile" "$expfile"
-     diff -b "$expfile" "$outfile"
+      diff -b "$expfile" "$outfile"
+result=$?
 
-if [ $? == 0 ]; then
+if [ $result == 0 ]; then
 	echo "  OK."
 else
+	exitcode=2
 	echo "  !!!!!!!!!!!!!!!!!!!!!!!!! FAILED !!!!!!!!!!!!!!!!!!!!!!!!!"
-	failed=1
 fi
 
-exit $failed
+exit $exitcode
 
 
 #-----------------------------------------------------------------------------
