Close #55: Non-const named() and positional()

diff --git a/test/_engine/run_case b/test/_engine/run_case
--- a/test/_engine/run_case
+++ b/test/_engine/run_case
@@ -11,7 +11,7 @@ fi
 
 #!!?? How much of the stuff below should actually go to init_per_case?... ;)
 
-case_path=`get_case_path $1` || FATAL "Test case \"$1\" not found!" 109
+case_path=`get_case_path $1` || FATAL "Test case \"$1\" not found!" $_ABORT_
 
 #!----------------------------------------------------------------------------
 #! Now we have a path to the test case (or ""!).
@@ -30,50 +30,79 @@ DEBUG "Identified \"$1\" as test case [$CASE] at \"$case_path\""
 echo "CASE: $CASE"
 
 if [ ! -d  "$case_path" ]; then
-	case_script="$case_path"
+	case_script_src="$case_path"
 	TEST_CASE_DIR=`dirname "$case_path"`
 else
-	case_script="$case_path/$TEST_CASE_SCRIPT_NAME"
+	case_script_src="$case_path/$TEST_CASE_SCRIPT_NAME"
 	TEST_CASE_DIR=$case_path
 fi
 
-if [ ! -e "$case_script" ]; then
-	FATAL "Test script not found: \"$case_script\"!"
+if [ ! -e "$case_script_src" ]; then
+	FATAL "Missing test script: \"$case_script_src\"!" $_ABORT_
 fi
 
-# Prep. the tmp work file locations...
-#! Note: preparing the exp. results file requires running the case script
-#!       first for its EXPECT clauses, if it has no standalone EXPECT file!
-outfile="${TMP_DIR}/${CASE}.out"
-errfile="${TMP_DIR}/${CASE}.err"
-retfile="${TMP_DIR}/${CASE}.retval"
-
-# Reset the work files...
-test -f "${outfile}" && rm "${outfile}"
-test -f "${errfile}" && rm "${errfile}"
-test -f "${retfile}" && rm "${retfile}"
-
-# Run a build for the test case if it seems to need one... (and $MAKE is set)
-build_dir "$TEST_CASE_DIR" || FATAL "Failed to build the test case!" $?
-
 #-----------------------------------
-# Finally, run (source) the case...
+# Prep. (wrap) the test script...
 #-----------------------------------
-exitcode=0
-EXPECT=
-case_variant_counter=0
+case_script="${TMP_DIR}/`basename \"$case_script_src\"`"
+	# Dir-local names in a flattened tree aren't unique, but no worries: they live per-case only!
 
-. "$case_script"
+echo -n "" > "$case_script" # CREATE_EMPTY
+#echo -n "ABORTED=\"$_TENTATIVE_ABORT_\"; " >> "$case_script" # Doing this without \n, so line numbers in errors wouldn't be off! :-o
+echo -n "CREATE_EMPTY \"$_TC_CRASHFILE\"; " >> "$case_script" # To be deleted on exit
+cat "$case_script_src"            >> "$case_script"
+echo ""                           >> "$case_script" # Nice catch! :) Scripts don't need to end with \n!
+echo "rm \"$_TC_CRASHFILE\""      >> "$case_script"
 
-retval=$?; if [ "$retval" != "0" ] || [ -s "$errfile" ]; then
-	ERROR "Test script unexpectedly crashed (with error $retval)!"
-	echo -e "  `cat \"$errfile\"`"
-	exit 109
+if [ ! -s "$case_script" ]; then
+	FATAL "Test script couldn't be copied to \"$case_script\" for processing!" $_ABORT_
 fi
 
-# Find or dyn. regenerate the expfile if defined in a .case script
-if [ -e     "$TEST_CASE_DIR/$EXPECT_FILE_NAME" ]; then
-    expfile="$TEST_CASE_DIR/$EXPECT_FILE_NAME"
+#-----------------------------------
+# Prep. the tmp work files...
+#-----------------------------------
+# Test (exec) steps...
+export cmdfile="${TMP_DIR}/${CASE}.cmd"
+export outfile="${TMP_DIR}/${CASE}.cmdout"
+export errfile="${TMP_DIR}/${CASE}.cmderr"
+#export retfile="${TMP_DIR}/${CASE}.cmdret"
+
+# Test case (script)...
+export expfile="${TMP_DIR}/${CASE}.expected"
+	#! Note: preparing the exp. results file requires running the case script
+	#!       first, for its EXPECT clauses, if it has no standalone EXPECT file!
+# !! To be accumulated and compared like EXPECT:
+#export retexpfile=${TMP_DIR}/${CASE}.retval.expected
+
+# Runner (meta) output...
+# Also using stderr, shared with the TC, so they remain in sync
+# (only the individual exed (RUN/SH) cmd's are redirected separately):
+export spacerrfile="${TMP_DIR}/${CASE}.spacerr"
+
+# Reset work files...
+# NOTE: They had only been deleted previously, but some scripts (like empty
+# ones...) won't create them, yet we'd still want to uniformly check them here.
+
+# Test (exec) steps...
+CREATE_EMPTY "${cmdfile}"
+CREATE_EMPTY "${outfile}"
+CREATE_EMPTY "${errfile}"
+#CREATE_EMPTY "${retfile}"
+# Test case (script)...
+CREATE_EMPTY "${expfile}"
+#CREATE_EMPTY "${retexpfile}"
+# Runner (meta) output...
+CREATE_EMPTY "${spacerrfile}"
+
+#-----------------------------------
+# Prepare the expected results...
+#-----------------------------------
+# Find (and copy, for some post-processing) a standalone EXPECT file.
+# NOTE: Preparing the in-script EXPCECT clauses is deferred until running
+#       the test script!
+static_expfile=
+if [ -e "$TEST_CASE_DIR/$EXPECT_FILE_NAME" ]; then
+	static_expfile="$TEST_CASE_DIR/$EXPECT_FILE_NAME"
 
 # NOTE:
 # In a mixed "GNU tools on Windows" env. (like mine) diff may not be able
@@ -83,35 +112,87 @@ if [ -e     "$TEST_CASE_DIR/$EXPECT_FILE_NAME" ]; then
 # and the user-supplied "expect" file -- which means we'd need to
 # "redirect" that too, the same way we do with an EXPECT clause.
 # (Because obviously we won't touch the opriginal file.)
-	kludge_expf="$TMP_DIR/${CASE}.expected"
 	# Better do this together with outfile, later below:
 	# tr -d '\015' < ${expfile} > "${kludge_expf}"
-	cp "$expfile" "$kludge_expf"
-	expfile=$kludge_expf
-else
-	expfile="$TMP_DIR/${CASE}.expected"
-	# $EXPECT must be quoted to preserve newlines.
-	# And mind the -n, too:
-	echo -n "$EXPECT" > "$expfile"
+	cp "$static_expfile" "$expfile"
 fi
 
-# Normalizing these would prevent precision-testing some whitespace handling, but the
-# CR/LF mismatches is a bigger issue anyway than what we could handle on this level...
-normalize_crlf "$expfile"
-normalize_crlf "$outfile"
+#-----------------------------------
+# Run a build for the test case if it needs one... (and $MAKE is set)
+#-----------------------------------
+build_dir "$TEST_CASE_DIR" || FATAL "Failed to build the test case!" $?
 
-#echo diff -b "$outfile" "$expfile"
-      diff -b "$expfile" "$outfile"
-result=$?
+#-----------------------------------
+# Finally, run (source) the case...
+#-----------------------------------
+# These are only exports to allow some wicked recursion hacks by users:
+export EXPECT=
+export EXPECT_ERROR=ignore
+export FORCED_RESULT=
+# This comes from the top-level (script) execution context:
+#export ABORTED=
+export case_variant_counter=0
 
-if [ $result == 0 ]; then
+# NOTE: thist script *itself* may get aborted on severe shell errors in the
+# TC, so we'd better output stderr early, while we still can!...
+
+savecd=`pwd`
+cd "${TEST_CASE_DIR}"
+	. "$case_script" 2> >(tee -a "$spacerrfile" >&2)
+	#. "$case_script" 2>> "$errfile"
+cd "${savecd}"
+
+
+testcase_status=0
+
+# Since there's no distinction between wrapper shell "syntax" errors
+# and the exit codes the actual commands return, this is just guesswork.
+# (In fact, the shell won't even return nonzero for some broken scripts,
+# e.g. with bad if "syntax": https://unix.stackexchange.com/a/650948/36398.)
+# But a good chunk of "meta" errors overlap with having stderr output...
+#!! Could also check a completion flag, though, like start with a "tentative"
+# ABORTED flag, which should be cleared at the end.
+retval=$?; if [ -s "$errfile" ] || [ ! -z "$ABORTED" ]; then
+	ERROR "Test script was terminated (with shell exit code $retval)!"
+	if [ ! -z "$ABORTED" ]; then DEBUG "ABORT req.: $ABORTED"; fi
+	DEBUG "accumulated cmd stderr: `cat \"$errfile\"`"
+	echo -e "  `cat \"$errfile\"`"
+	echo "  !!!!!!!!!!!!!!!!!!!!!!!!! ABORTED !!!!!!!!!!!!!!!!!!!!!!!!!"
+	exit $_ABORT_
+fi
+
+# Forced fail/pass?
+if [ ! -z "$FORCED_RESULT" ]; then testcase_status=$FORCED_RESULT; fi
+
+#-----------------------------------
+# Diff the result (if we're still in the green)
+#-----------------------------------
+if [ "$testcase_status" == "0" ]; then
+	# In-script EXPECT? (Can't decide based on $EXPECT, as it can be empty!)
+	if [ -z "$static_expfile" ]; then
+		# $EXPECT must be quoted to preserve newlines. And mind the -n, too:
+		echo -n "$EXPECT" > "$expfile"
+	fi
+
+	normalize_crlf "$expfile"
+	normalize_crlf "$outfile"
+		# These would prevent precise testing of whitespace in outputs, but CR/LF
+		# mismatches is a bigger issue than what we could handle on this level...
+
+	#echo diff -b "$outfile" "$expfile"
+	diff -b "$outfile" "$expfile"
+	diff_result=$?
+
+	if [ "$diff_result" != "0" ]; then testcase_status=15; fi
+fi
+
+if [ "$testcase_status" == "0" ]; then
 	echo "  OK."
 else
-	exitcode=2
-	echo "  !!!!!!!!!!!!!!!!!!!!!!!!! FAILED !!!!!!!!!!!!!!!!!!!!!!!!!"
+	echo "  !!!!!!!!!!!!!!!!!!!!!!!!! FAILED !!!!!!!!!!!!!!!!!!!!!!!!! (status: $testcase_status)"
 fi
 
-exit $exitcode
+exit $testcase_status
 
 
 #-----------------------------------------------------------------------------
